// Turns a deployed contract into a working, standalone web app.
//
// Deterministic and pure: same spec in, same files out, no network, no model.
// That is deliberate: the app's binding to the contract (address, chain, ABI,
// argument encoding) is generated by code so it is correct by construction.
// The AI refines app.js and styles.css afterwards; it never authors
// contract.js, so a bad model response can restyle the app but cannot point it
// at the wrong contract or mis-encode a call.
//
// Two shapes come out of here, and the difference is only ever packaging:
//
//   "esm" : no build step at all. ES modules plus an import map, so one
//            folder serves the preview, the downloaded zip and a live
//            deployment. Works with no infrastructure whatsoever.
//   "vite": the same modules as a real project: dependencies from npm, a
//            bundler, and a toolchain the agent can actually run. Needs the
//            build runner (services/runner), so it is only offered when one is
//            configured.
//
// The application files are byte-for-byte identical between the two. They
// import bare specifiers ("preact/hooks", "viem") and relative paths, which an
// import map resolves in the browser and Vite resolves from node_modules, so
// nothing about the app has to know which target it was generated for. Only
// the shell around it differs: an import map, or a package.json.

import { ABI_UI_JS, APP_JS, STYLES_CSS, WALLET_JS } from "./runtime";

/** Pinned so a generated app keeps working when these packages move on.
 *  Verified to resolve on esm.sh before being baked in. */
export const CDN_VERSIONS = {
  preact: "10.24.3",
  htm: "3.1.1",
  viem: "2.52.0",
} as const;

/** npm dependencies for the "vite" target, pinned to the same versions the
 *  import map uses so an app behaves identically whichever way it was built.
 *
 *  Mirrored in services/runner/warm-package.json, which pre-installs exactly
 *  this set into the runner image. Change these and that file together, or
 *  every job pays for a cold install, which took 175s against a 180s phase
 *  deadline when it was measured. */
export const VITE_DEPS = {
  dependencies: {
    preact: CDN_VERSIONS.preact,
    htm: CDN_VERSIONS.htm,
    viem: CDN_VERSIONS.viem,
  },
  devDependencies: {
    vite: "7.1.5",
    // Gives the model the option of writing JSX. The generated files use htm
    // instead, which needs no transform; both produce preact elements, so the
    // two mix freely in one project.
    "@preact/preset-vite": "2.10.6",
    "@playwright/test": "1.62.1",
    eslint: "9.39.5",
    "@eslint/js": "9.39.5",
    globals: "17.11.0",
  },
} as const;

/** How the app is packaged. See the note at the top of this file. */
export type BuildTarget = "esm" | "vite";

export interface GenerateSpec {
  /** Contract ABI, already validated (see abi-source.ts). */
  abi: unknown[];
  address: `0x${string}`;
  /** Display name for the app. Falls back to a generic title. */
  contractName?: string | null;
  chainId: number;
  chainName: string;
  rpcUrl: string;
  explorerUrl: string;
  /** Native token symbol, e.g. "QIE" or "BOT". */
  nativeSymbol: string;
  /** Directory the files are written under, inside the workspace. */
  dir?: string;
  /** Defaults to "esm", which needs nothing to run. The App Builder asks for
   *  "vite" when the deployment has a build runner. */
  target?: BuildTarget;
}

export type GeneratedFiles = Record<string, string>;

/** Files the AI may rewrite. contract.js is deliberately excluded. */
export const AI_EDITABLE = ["app.js", "styles.css", "index.html"] as const;
/** Regenerated from the contract; never hand-written or model-written. */
export const GENERATED_ONLY = ["contract.js"] as const;

/** Where the application files sit within the project.
 *
 *  A Vite project keeps its source under src/ and its configuration at the
 *  root, which is the convention every tool and every model already expects.
 *  The no-build layout is flat, because it is served as-is. */
function sourceDir(target: BuildTarget): string {
  return target === "vite" ? "src/" : "";
}

function safeName(raw: string | null | undefined): string {
  const cleaned = (raw ?? "").replace(/[^A-Za-z0-9 _-]/g, "").trim();
  return cleaned || "Contract";
}

function slug(raw: string): string {
  return (
    raw
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "dapp"
  );
}

/** JSON that is safe to inline inside a <script type="module"> / .js file. */
function inlineJson(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function contractJs(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  return `// GENERATED: do not edit by hand.
//
// This file is what binds the app to your deployed contract. DevStation
// regenerates it from the contract itself, so editing it (or asking the agent
// to) is the one way to make the rest of the app talk to the wrong thing.
// Everything else in this project is yours to change.

export const CHAIN = {
  id: ${spec.chainId},
  name: ${JSON.stringify(spec.chainName)},
  symbol: ${JSON.stringify(spec.nativeSymbol)},
  rpcUrl: ${JSON.stringify(spec.rpcUrl)},
  explorerUrl: ${JSON.stringify(spec.explorerUrl)},
};

export const CONTRACT = {
  name: ${JSON.stringify(name)},
  address: ${JSON.stringify(spec.address)},
  abi: ${inlineJson(spec.abi)},
};
`;
}

function viteIndexHtml(title: string): string {
  const name = title;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}</title>
    <link rel="stylesheet" href="/src/styles.css" />
    <!--
      No import map: Vite resolves "preact", "htm/preact" and "viem" from
      node_modules and bundles them, so the same app.js works here and in the
      no-build build.
    -->
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/app.js"></script>
  </body>
</html>
`;
}

function viteEslintConfig(): string {
  return `import js from "@eslint/js";
import globals from "globals";

export default [
  { ignores: ["dist"] },
  {
    files: ["**/*.js", "**/*.jsx"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: globals.browser,
    },
    rules: {
      ...js.configs.recommended.rules,
      // The wallet bridge and the ABI helpers both catch and ignore failures
      // deliberately, where there is nothing useful to do with the error.
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  {
    files: ["tests/**/*.js", "*.config.js"],
    languageOptions: { globals: globals.node },
  },
];
`;
}

function vitePlaywrightConfig(): string {
  return `import { defineConfig } from "@playwright/test";

const HOST = "127.0.0.1";
const PORT = 4173;

export default defineConfig({
  testDir: "./tests",
  timeout: 30_000,
  use: { baseURL: \`http://\${HOST}:\${PORT}\` },
  webServer: {
    // Tests run against the built output, which is what actually ships.
    //
    // --host is not optional. Left to itself vite binds "localhost", which
    // resolves to ::1 first in a container, while Playwright polls 127.0.0.1
    // and waits out its full timeout against a server that is running
    // perfectly well on the other loopback address.
    command: \`npm run preview -- --host \${HOST} --port \${PORT} --strictPort\`,
    url: \`http://127.0.0.1:\${PORT}\`,
    reuseExistingServer: false,
    timeout: 60_000,
  },
});
`;
}

function viteSmokeTest(title: string): string {
  const name = title;
  return `import { test, expect } from "@playwright/test";

// Does the app actually come up? That is the question the preview could never
// answer on its own: a page that throws while mounting looks exactly like a
// page that is still loading.
//
// Add your own tests below. This one is the floor, not the ceiling.

test("${name.replace(/"/g, "")} renders", async ({ page }) => {
  const problems = [];
  page.on("pageerror", (e) => problems.push(String(e)));
  page.on("console", (m) => {
    if (m.type() !== "error") return;
    // The test sandbox has no network, on purpose: nothing after the install
    // step can reach out. So the app's RPC calls fail here, and that says
    // nothing about whether the app works. Everything else counts.
    if (/fetch|network|ERR_|ECONN|Failed to load resource/i.test(m.text())) return;
    problems.push(m.text());
  });

  await page.goto("/");
  await expect(page.locator("#root")).not.toBeEmpty();
  expect(problems).toEqual([]);
});
`;
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import preact from "@preact/preset-vite";

export default defineConfig({
  plugins: [preact()],
  // Relative asset paths, so the built output works from a subdirectory and
  // inside DevStation's sandboxed preview, which has no origin to be
  // absolute against.
  base: "./",
});
`;
}

function indexHtml(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  const { preact, htm, viem } = CDN_VERSIONS;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}: ${spec.chainName}</title>
    <link rel="stylesheet" href="./styles.css" />
    <!--
      No build step. The import map resolves bare specifiers straight from a
      CDN, which is what lets this same folder run as a preview, as a download
      you can open locally, and as a deployed site.
    -->
    <script type="importmap">
      {
        "imports": {
          "preact": "https://esm.sh/preact@${preact}",
          "preact/hooks": "https://esm.sh/preact@${preact}/hooks",
          "htm/preact": "https://esm.sh/htm@${htm}/preact?deps=preact@${preact}",
          "viem": "https://esm.sh/viem@${viem}"
        }
      }
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./app.js"></script>
  </body>
</html>
`;
}

function readme(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  return `# ${name}

A web app for [\`${spec.address}\`](${spec.explorerUrl.replace(/\/$/, "")}/address/${spec.address})
on ${spec.chainName}, generated by [DevStation](https://devstation.online).

## Run it

There is no build step and nothing to install:

\`\`\`bash
npx serve .
\`\`\`

Opening \`index.html\` directly from the filesystem will not work: browsers
block ES module imports over \`file://\`. Any static server is fine.

## Deploy it

These are plain static files. Drop the folder on Netlify, Vercel, GitHub
Pages, Cloudflare Pages, or any static host. No server, no environment
variables, no build command.

## The files

| File | What it is |
|---|---|
| \`index.html\` | Page shell and the import map pinning preact, htm and viem |
| \`app.js\` | The UI. **Yours to change.** |
| \`styles.css\` | Styling. **Yours to change.** |
| \`abi-ui.js\` | Maps ABI types to form controls and parses what you type |
| \`wallet.js\` | Wallet access (\`window.ethereum\`, or DevStation's preview bridge) |
| \`contract.js\` | **Generated.** Address, chain and ABI. Do not edit by hand. |

## Notes

Reads go straight to the RPC, so they work before you connect a wallet.
Sending a transaction needs a wallet on ${spec.chainName} (chain id
${spec.chainId}).

Functions taking tuples or nested arrays are shown but disabled: encoding
those from a text field is guesswork, and a wrong encoding produces a
transaction that looks fine and does the wrong thing. Call them from code.
`;
}

function vitePackageJson(title: string, description: string): string {
  return (
    JSON.stringify(
      {
        name: slug(title) + "-dapp",
        private: true,
        version: "1.0.0",
        type: "module",
        description,
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
          lint: "eslint .",
          test: "playwright test",
        },
        dependencies: { ...VITE_DEPS.dependencies },
        devDependencies: { ...VITE_DEPS.devDependencies },
      },
      null,
      2,
    ) + "\n"
  );
}

function packageJson(spec: GenerateSpec): string {
  return (
    JSON.stringify(
      {
        name: slug(safeName(spec.contractName)) + "-dapp",
        private: true,
        version: "1.0.0",
        description: `Generated by DevStation for ${spec.address} on ${spec.chainName}`,
        scripts: {
          // No build: the app is already runnable ES modules.
          start: "npx --yes serve .",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function viteReadme(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  return `# ${name}

A web app for [\`${spec.address}\`](${spec.explorerUrl.replace(/\/$/, "")}/address/${spec.address})
on ${spec.chainName}, generated by [DevStation](https://devstation.online).

An ordinary Vite project: clone it, add packages, and deploy it anywhere.

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

\`npm run build\` writes static files to \`dist/\`, which any static host will
serve: Netlify, Vercel, GitHub Pages, Cloudflare Pages. No server and no
environment variables.

## The files

| File | What it is |
|---|---|
| \`index.html\` | Page shell |
| \`vite.config.js\` | Build configuration |
| \`src/app.js\` | The UI. **Yours to change.** |
| \`src/styles.css\` | Styling. **Yours to change.** |
| \`src/abi-ui.js\` | Maps ABI types to form controls and parses what you type |
| \`src/wallet.js\` | Wallet access (\`window.ethereum\`, or DevStation's preview bridge) |
| \`src/contract.js\` | **Generated.** Address, chain and ABI. Do not edit by hand. |

The UI is written with [htm](https://github.com/developit/htm), which is JSX's
syntax as a tagged template and needs no build step of its own. JSX works too -
\`@preact/preset-vite\` is configured, so \`.jsx\` files can sit alongside these.

## Notes

Reads go straight to the RPC, so they work before you connect a wallet.
Sending a transaction needs a wallet on ${spec.chainName} (chain id
${spec.chainId}).

Functions taking tuples or nested arrays are shown but disabled: encoding
those from a text field is guesswork, and a wrong encoding produces a
transaction that looks fine and does the wrong thing. Call them from code.
`;
}

/**
 * The project around the app: build config, lint config, browser test setup.
 *
 * Shared by a generated app and an empty one so the two cannot drift: an
 * empty project that lints differently from a generated one is a trap, since
 * the agent's whole feedback loop runs through these files.
 */
export function viteShell(
  title: string,
  options: { dir?: string; description?: string } = {},
): GeneratedFiles {
  const dir = (options.dir ?? "app").replace(/^\/+|\/+$/g, "");
  const at = (name: string) => (dir ? `${dir}/${name}` : name);
  return {
    [at("index.html")]: viteIndexHtml(title),
    [at("vite.config.js")]: viteConfig(),
    [at("eslint.config.js")]: viteEslintConfig(),
    [at("playwright.config.js")]: vitePlaywrightConfig(),
    [at("tests/app.spec.js")]: viteSmokeTest(title),
    [at("package.json")]: vitePackageJson(
      title,
      options.description ?? `${title}, generated by DevStation`,
    ),
  };
}

/**
 * Generate a complete, runnable app for a contract.
 * Returns a path → content map, ready to write into the workspace.
 */
export function generateApp(spec: GenerateSpec): GeneratedFiles {
  const dir = (spec.dir ?? "app").replace(/^\/+|\/+$/g, "");
  const at = (name: string) => (dir ? `${dir}/${name}` : name);
  const src = sourceDir(spec.target ?? "esm");

  // Identical in both targets, and deliberately so: whichever way the app is
  // packaged, it is the same application.
  const app: GeneratedFiles = {
    [at(`${src}app.js`)]: APP_JS,
    [at(`${src}abi-ui.js`)]: ABI_UI_JS,
    [at(`${src}wallet.js`)]: WALLET_JS,
    [at(`${src}contract.js`)]: contractJs(spec),
    [at(`${src}styles.css`)]: STYLES_CSS,
  };

  if ((spec.target ?? "esm") === "vite") {
    return {
      ...app,
      ...viteShell(safeName(spec.contractName), {
        dir,
        description: `Generated by DevStation for ${spec.address} on ${spec.chainName}`,
      }),
      [at("README.md")]: viteReadme(spec),
    };
  }

  return {
    ...app,
    [at("index.html")]: indexHtml(spec),
    [at("README.md")]: readme(spec),
    [at("package.json")]: packageJson(spec),
  };
}

/** Only the contract binding, for refreshing after a redeploy without
 *  discarding UI edits. */
export function regenerateContractFile(spec: GenerateSpec): { path: string; content: string } {
  const dir = (spec.dir ?? "app").replace(/^\/+|\/+$/g, "");
  const name = `${sourceDir(spec.target ?? "esm")}contract.js`;
  return { path: dir ? `${dir}/${name}` : name, content: contractJs(spec) };
}
