// Turns a deployed contract into a working, standalone web app.
//
// Deterministic and pure: same spec in, same files out, no network, no model.
// That is deliberate — the app's binding to the contract (address, chain, ABI,
// argument encoding) is generated by code so it is correct by construction.
// The AI refines app.js and styles.css afterwards; it never authors
// contract.js, so a bad model response can restyle the app but cannot point it
// at the wrong contract or mis-encode a call.
//
// The output has NO build step: ES modules plus an import map, so one artifact
// serves the in-app preview, the downloaded zip and a live deployment.

import { ABI_UI_JS, APP_JS, STYLES_CSS, WALLET_JS } from "./runtime";

/** Pinned so a generated app keeps working when these packages move on.
 *  Verified to resolve on esm.sh before being baked in. */
export const CDN_VERSIONS = {
  preact: "10.24.3",
  htm: "3.1.1",
  viem: "2.52.0",
} as const;

export interface GenerateSpec {
  /** Contract ABI, already validated (see abi-source.ts). */
  abi: unknown[];
  address: `0x${string}`;
  /** Display name for the app. Falls back to a generic title. */
  contractName?: string | null;
  chainId: number;
  chainName: string;
  rpcUrl: string;
  explorerUrl: string;
  /** Native token symbol, e.g. "QIE" or "BOT". */
  nativeSymbol: string;
  /** Directory the files are written under, inside the workspace. */
  dir?: string;
}

export type GeneratedFiles = Record<string, string>;

/** Files the AI may rewrite. contract.js is deliberately excluded. */
export const AI_EDITABLE = ["app.js", "styles.css", "index.html"] as const;
/** Regenerated from the contract; never hand-written or model-written. */
export const GENERATED_ONLY = ["contract.js"] as const;

function safeName(raw: string | null | undefined): string {
  const cleaned = (raw ?? "").replace(/[^A-Za-z0-9 _-]/g, "").trim();
  return cleaned || "Contract";
}

function slug(raw: string): string {
  return (
    raw
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "dapp"
  );
}

/** JSON that is safe to inline inside a <script type="module"> / .js file. */
function inlineJson(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function contractJs(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  return `// GENERATED — do not edit by hand.
//
// This file is what binds the app to your deployed contract. DevStation
// regenerates it from the contract itself, so editing it (or asking the agent
// to) is the one way to make the rest of the app talk to the wrong thing.
// Everything else in this project is yours to change.

export const CHAIN = {
  id: ${spec.chainId},
  name: ${JSON.stringify(spec.chainName)},
  symbol: ${JSON.stringify(spec.nativeSymbol)},
  rpcUrl: ${JSON.stringify(spec.rpcUrl)},
  explorerUrl: ${JSON.stringify(spec.explorerUrl)},
};

export const CONTRACT = {
  name: ${JSON.stringify(name)},
  address: ${JSON.stringify(spec.address)},
  abi: ${inlineJson(spec.abi)},
};
`;
}

function indexHtml(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  const { preact, htm, viem } = CDN_VERSIONS;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name} — ${spec.chainName}</title>
    <link rel="stylesheet" href="./styles.css" />
    <!--
      No build step. The import map resolves bare specifiers straight from a
      CDN, which is what lets this same folder run as a preview, as a download
      you can open locally, and as a deployed site.
    -->
    <script type="importmap">
      {
        "imports": {
          "preact": "https://esm.sh/preact@${preact}",
          "preact/hooks": "https://esm.sh/preact@${preact}/hooks",
          "htm/preact": "https://esm.sh/htm@${htm}/preact?deps=preact@${preact}",
          "viem": "https://esm.sh/viem@${viem}"
        }
      }
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./app.js"></script>
  </body>
</html>
`;
}

function readme(spec: GenerateSpec): string {
  const name = safeName(spec.contractName);
  return `# ${name}

A web app for [\`${spec.address}\`](${spec.explorerUrl.replace(/\/$/, "")}/address/${spec.address})
on ${spec.chainName}, generated by [DevStation](https://devstation.online).

## Run it

There is no build step and nothing to install:

\`\`\`bash
npx serve .
\`\`\`

Opening \`index.html\` directly from the filesystem will not work — browsers
block ES module imports over \`file://\`. Any static server is fine.

## Deploy it

These are plain static files. Drop the folder on Netlify, Vercel, GitHub
Pages, Cloudflare Pages, or any static host. No server, no environment
variables, no build command.

## The files

| File | What it is |
|---|---|
| \`index.html\` | Page shell and the import map pinning preact, htm and viem |
| \`app.js\` | The UI. **Yours to change.** |
| \`styles.css\` | Styling. **Yours to change.** |
| \`abi-ui.js\` | Maps ABI types to form controls and parses what you type |
| \`wallet.js\` | Wallet access (\`window.ethereum\`, or DevStation's preview bridge) |
| \`contract.js\` | **Generated.** Address, chain and ABI. Do not edit by hand. |

## Notes

Reads go straight to the RPC, so they work before you connect a wallet.
Sending a transaction needs a wallet on ${spec.chainName} (chain id
${spec.chainId}).

Functions taking tuples or nested arrays are shown but disabled: encoding
those from a text field is guesswork, and a wrong encoding produces a
transaction that looks fine and does the wrong thing. Call them from code.
`;
}

function packageJson(spec: GenerateSpec): string {
  return (
    JSON.stringify(
      {
        name: slug(safeName(spec.contractName)) + "-dapp",
        private: true,
        version: "1.0.0",
        description: `Generated by DevStation for ${spec.address} on ${spec.chainName}`,
        scripts: {
          // No build: the app is already runnable ES modules.
          start: "npx --yes serve .",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * Generate a complete, runnable app for a contract.
 * Returns a path → content map, ready to write into the workspace.
 */
export function generateApp(spec: GenerateSpec): GeneratedFiles {
  const dir = (spec.dir ?? "app").replace(/^\/+|\/+$/g, "");
  const at = (name: string) => (dir ? `${dir}/${name}` : name);
  return {
    [at("index.html")]: indexHtml(spec),
    [at("app.js")]: APP_JS,
    [at("abi-ui.js")]: ABI_UI_JS,
    [at("wallet.js")]: WALLET_JS,
    [at("contract.js")]: contractJs(spec),
    [at("styles.css")]: STYLES_CSS,
    [at("README.md")]: readme(spec),
    [at("package.json")]: packageJson(spec),
  };
}

/** Only the contract binding, for refreshing after a redeploy without
 *  discarding UI edits. */
export function regenerateContractFile(spec: GenerateSpec): { path: string; content: string } {
  const dir = (spec.dir ?? "app").replace(/^\/+|\/+$/g, "");
  return { path: dir ? `${dir}/contract.js` : "contract.js", content: contractJs(spec) };
}
