// Compiles the DevStation contracts with solc and writes:
//   - contracts/out/<Name>.json       (full standard-JSON artifact)
//   - src/lib/abis/<name>.ts          (typed ABI + bytecode for the frontend)
//
// Run: bun run scripts/compile.ts
// Uses the bundled solc version (no network needed when solc ships its binary).
import solc from "solc";
import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const CONTRACTS = ["ProjectRegistry", "ContractLabelRegistry"];

function readSource(name: string): string {
  return fs.readFileSync(path.join(ROOT, "contracts", `${name}.sol`), "utf8");
}

const input = {
  language: "Solidity",
  sources: Object.fromEntries(CONTRACTS.map((n) => [`${n}.sol`, { content: readSource(n) }])),
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

console.log(`solc version: ${solc.version()}`);
const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []).filter((e: { severity: string }) => e.severity === "error");
if (errors.length > 0) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}
for (const w of output.errors ?? []) {
  console.warn(w.formattedMessage);
}

const outDir = path.join(ROOT, "contracts", "out");
const abiDir = path.join(ROOT, "src", "lib", "abis");
fs.mkdirSync(outDir, { recursive: true });
fs.mkdirSync(abiDir, { recursive: true });

for (const name of CONTRACTS) {
  const contract = output.contracts[`${name}.sol`][name];
  const abi = contract.abi;
  const bytecode = `0x${contract.evm.bytecode.object}`;

  fs.writeFileSync(path.join(outDir, `${name}.json`), JSON.stringify({ abi, bytecode }, null, 2));

  const camel = name.charAt(0).toLowerCase() + name.slice(1);
  const ts = `// AUTO-GENERATED by scripts/compile.ts — do not edit by hand.
export const ${camel}Abi = ${JSON.stringify(abi)} as const;

export const ${camel}Bytecode = "${bytecode}" as \`0x\${string}\`;
`;
  fs.writeFileSync(path.join(abiDir, `${camel}.ts`), ts);
  console.log(`✓ ${name}: ${abi.length} ABI entries, ${(bytecode.length - 2) / 2} bytes`);
}

console.log("Done. ABIs written to src/lib/abis/, artifacts to contracts/out/.");
